language: rust
rust:
  - stable
  - beta
notifications:
  email:
    - adolphc@outlook.com
before_script:
  - export PORTAUDIO_ONLY_STATIC=true
  - rustc --version
  - cargo --version
branches:
  only:
    - master
    - development