language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  email:
    - adolphc@outlook.com
before_script:
  - git submodule update --init --recursive
script:
  - rustc --version
  - cargo --version
branches:
  only:
    - master