[package]
name = "pyrite"
version = "0.1.0"
authors = ["Adolph C. <adolph.celestin@gmail.com>"]

[profile.dev]
opt-level = 3
# Ideally I would just like to turn overflow checking off
# because overflows happen so frequently, but this is fine I guess.
debug-assertions = false

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
