#!/bin/bash

echo "Disassembling Custom Roms..."

ARM_DEST="disasm-arm.s"
THUMB_DEST="disasm-thumb.s"

ARM_DISASM="../../target/release/pyrite"
if [ ! -f "${ARM_DISASM}" ]; then
	echo "Falling back on debug"
	ARM_DISASM="../../target/debug/pyrite"
	if [ ! -f "${ARM_DISASM}" ]; then
		echo "No Pyrite binaries found."
		exit 1
	fi
fi

echo "Deleting Old Files..."
rm "${ARM_DEST}" >> /dev/null
rm "${THUMB_DEST}" >> /dev/null

echo "Disassembling ARM..."
$ARM_DISASM -d "custom_mb.gba" >> "${ARM_DEST}"

echo "Disassembling THUMB..."
$ARM_DISASM -d -t "custom_mb.gba" >> "${THUMB_DEST}"

echo "Finished."
